//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test2.proto
// Note: requires additional types generated from: test1.proto
namespace Test.App
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuperHero")]
  public partial class SuperHero : global::ProtoBuf.IExtensible
  {
    public SuperHero() {}
    
    private Test.Base.Hero _hero;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Test.Base.Hero hero
    {
      get { return _hero; }
      set { _hero = value; }
    }
    private string _superSkill;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"superSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string superSkill
    {
      get { return _superSkill; }
      set { _superSkill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}